### ISSUE TITLE
Running unit tests copies resources into classes folder

### ISSUE THREAD

**Issue by boaty82** [epam/sap-commerce-intellij-idea-plugin#1011]
long time user of plugin here, good work btw!

Since taking a recent update to IntelliJ and the plugin, when I compile code (which obviously running unit tests does) the contents within the resources folder ends up in the classes directory

This causes us a problem, as we have release scripts in our resources folder. We validate these as part of the build.

So once I've run unit tests I have to delete the copies within the classes directory, if I do not our validation build call back fails as it finds the same files in the resources folder AND the classes folder

![Screenshot 2024-02-15 at 14 38 19](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/8507223/a8894823-0766-4980-a707-22857c02f495)

**Comment by mlytvyn** [comment]
@boaty82 , thank you for highlighting this and screenshot, it always helps!

**Comment by mlytvyn** [comment]
@boaty82 , to overcome this custom project setup we will introduce possibility to specify output path for custom extensions during the project import or via Project Refresh Settings later.
By default, it will point to `classes`, otherwise to fake path `eclipsebin`.

It will be part of the next `2024.1.0` release.

**Comment by boaty82** [comment]
@mlytvyn sounds good, thanks for the quick reply

I've also noticed this issue affects impex by convention during initialization.  Hybris is reporting it found two files with the same name and that I should choose "unique" names

**Comment by mlytvyn** [comment]
Introduced new flag for output paths in the #1012.
