### ISSUE TITLE
Not possible to run unit tests

### ISSUE THREAD

**Issue by YevheniiChernikhovskyi** [epam/sap-commerce-intellij-idea-plugin#1077]
IntelliJ IDEA 2023.3.6 (Community Edition)
The latest plugin version.

If I try to run Unit Test it will fail
<img width="924" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/11999799/fc0dffd4-7252-4c5c-aeae-32c6eb6cbc5f">
and all models will be removed.
If the plugin is disabled and test is executed again, it will run successfully
Thanks.

**Comment by mlytvyn** [comment]
@YevheniiChernikhovskyi , check details of the log output, try to extend timeout, if nothing helps -> disable generation.
<img width="884" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/ebb123e0-f252-4406-bce0-b8c0f7ae85d3">

**Comment by YevheniiChernikhovskyi** [comment]
@mlytvyn , thanks, it works, closing the issues
