### ISSUE TITLE
Import does not work with overridden custom directory

### ISSUE THREAD

**Issue by dev-jan** [epam/sap-commerce-intellij-idea-plugin#1083]
Hi!

First of all, thanks for the great plugin! We currently have a problem using the newest released version of the plugin with our project structure. We override the "custom" directory, since in our repo structure, we didn't name it "custom", but "ext-ourCompany". This was not a problem with version 2022.2, as our modules are correctly imported as custom modules.

With the new version, they are imported like the Hybris built-in modules. Understandable, since the format matches the standard Hybris modules format, but we override the customs directory, but it seems like to not work.

Our repo structure:
```
- mainfolder
-- hybris
--- bin
---- platform
---- modules
---- ext-ourCompany  # our custom extensions live here
----- someCustomModule
--- config
```

Hope you can help us :)

**Comment by mlytvyn** [comment]
@dev-jan , thank you for raising this, can you please remind me how to override custom directory?

**Comment by dev-jan** [comment]
The custom directory can be modified while importing the project for the first time @mlytvyn 

I think I found the problem in the extension, but I was not able to fully build it. Can you test my Pull Request and see if that worked? Looks like a copy past error to me ;)

**Comment by mlytvyn** [comment]
@dev-jan , report an issue -> close an issue! not a contributor -> a dream :) 

thank you for your contribution and looking forward to your ideas / suggestions.
