### ISSUE TITLE
CCv2 integration is not returning any information

### ISSUE THREAD

**Issue by andy-kru** [epam/sap-commerce-intellij-idea-plugin#1100]
I'm trying to check a new plugin feature with CCv2 integration, but unfortunately, I'm not able to fetch any data:
![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/45319374/45aa6a88-4eca-46e9-a7d9-461cc1271e42)
I'm using Windows 11 + SapMachine 17 and I'm able to fetch data manually with CLI tool:
![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/45319374/e998f720-97e6-4891-8623-71142936815e)
There are no errors/warnings in the IDEA, is there anything else I can check?

**Comment by mlytvyn** [comment]
@andy-kru , can you please join project Slack so we can check it together?

**Comment by mlytvyn** [comment]
@andy-kru , btw, can you please try `Native` integration mode?

most probably there is OS specific issue and I do not have Windows OS to check it on my side.

**Comment by mlytvyn** [comment]
@andy-kru , ah, yes, have you clicked "Fetch" button - left vertical action panel?
<img width="368" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/feec3ea6-2d04-4a66-8d87-6647e13f4721">

**Comment by mlytvyn** [comment]
SAP CCM integration does not work for Windows OS, @everyone, please use `Native` (https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/1071).

SAP CCM support is removed in the upcoming release 2024.1.2 and I'll focus only on `Native` REST integration.
