### ISSUE TITLE
Unable to fetch CCv2 information if user have any subscription without environment permission

### ISSUE THREAD

**Issue by andy-kru** [epam/sap-commerce-intellij-idea-plugin#1194]
Hi!

I'm trying to test CCv2 integration in the plugin and constantly getting the same error during the "Fetch Environments" step:
`Subscription: subscription02 Non-null value 'environments' was null at $.permissionDTOS[0].environments`

I have multiple subscriptions linked to my account, but they all failed with the same message. I see there is a code to extract allowed environments from the permission object https://github.com/epam/sap-commerce-intellij-idea-plugin/blob/main/src/com/intellij/idea/plugin/hybris/tools/ccv2/api/CCv2Api.kt#L85

But in my case, I have pretty old subscriptions where `"environments": null` and I can access their environments through a web portal.

GET: https://portal.commerce.ondemand.com/v1/permissions
```json
{
    "username": "ccv2username",
    "permissionDTOS": [
        {
            "scopeName": "subscription01",
            "permissions": [
                "..."
            ],
            "environments": null
        },
        {
            "scopeName": "subscription02",
            "permissions": [
                "..."
            ],
            "environments": [
                "d1",
                "p1",
                "s1"
            ]
        }
    ]
}
```

Currently, there is no way to get the status of any subscription if the account has at least one subscription with `"environments": null`.

**Comment by mlytvyn** [comment]
@andy-kru , cool finding!!! could you please reach me out in the Slack for a short sync-up?

**Comment by mlytvyn** [comment]
fixed

**Comment by superpalmi** [comment]
hi @mlytvyn I'm having issues fetching environment data:
![image](https://github.com/user-attachments/assets/f50da945-22da-4aa0-9a90-b308b31e9767)
I'm using the same token and subscriptionId as the ones sent via curl and it's working correctly, should I open an Issue or i am missing something?

Thank you

**Comment by cah-mykhailo-lytvyn** [comment]
@superpalmi , yeah, let's have another issue; feel free to sync-up in Slack chat for a quick call on this issue.
