### ISSUE TITLE
Impex: Resolve correct value

### ISSUE THREAD

**Issue by tomzi8571** [epam/sap-commerce-intellij-idea-plugin#1206]
When resolving a value it takes the last from the file instead the recent one

![image](https://github.com/user-attachments/assets/283610cd-7a57-4cc4-88b9-babcc3124172)

**Comment by mlytvyn** [comment]
@tomzi8571 , thank you for highlighting this issue, it was not easy one, but I hope to get it solved with the https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/1260.

in addition to that I've identified multiple other issues for such cases, which I will try to address soon, thank you!
