### ISSUE TITLE
hybris is not available in tool windows

### ISSUE THREAD

**Issue by khalid-sb** [epam/sap-commerce-intellij-idea-plugin#121]
hi, after importing project using : 
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
plugin version : 2022.3.0

hybris is not available in view >> tool windows 
![image](https://user-images.githubusercontent.com/20110054/210250991-ac671c9a-7bbb-4b36-941b-515bd12e28b2.png)

**Comment by khalid-sb** [comment]
after upgarding IntelliJ to 2022.3.1 the problem is fixed

**Comment by mlytvyn** [comment]
hello @khalid-sb , actually problem is slightly different here.

[y] tool window will not appear right away after project import, one have to restart IDEA to make it visible.

thank you for reporting, I'll check what can be done.

**Comment by mlytvyn** [comment]
fixed
