### ISSUE TITLE
question: how can I add the extension to the project after creation?

### ISSUE THREAD

**Issue by thetruechar** [epam/sap-commerce-intellij-idea-plugin#1252]
After creating the extension using ant extgen, how can I add to the project? Thanks.

**Comment by mlytvyn** [comment]
> After creating the extension using ant extgen, how can I add to the project? Thanks.

Hello, 

Once extension added to the localextensions.xml or as a dependency to those already in use, you can refresh the project from the File menu.

**Comment by thetruechar** [comment]
thanks.
