### ISSUE TITLE
Project import or "Refresh SAP Commerce Project" stuck on "Scanning SAP Commerce Projects"

### ISSUE THREAD

**Issue by mburakgurler** [epam/sap-commerce-intellij-idea-plugin#1285]
### Environment Details
- **IntelliJ IDEA Version**: IntelliJ IDEA 2024.3.1
- **SAP Commerce IntelliJ Plugin Version**: 2024.3.2
- **Operating System**: Ubuntu 24.04 (via WSL2 on Windows 11)
- **Java Version**: Oracle JDK 11
- **SAP Commerce Version**: 2105
- Log from importing: [idea.log](https://github.com/user-attachments/files/18084822/idea.log)

The import process gets stuck indefinitely on "Scanning SAP Commerce Projects."
- Tried clearing caches and restarting IntelliJ with disabling all other plugins but faced the same issue.
![image](https://github.com/user-attachments/assets/de9ec5aa-ba9a-45bb-96be-0710a8f6f131)

**Comment by mlytvyn** [comment]
Hello @mburakgurler, wsl is not fully or even partially supported by the plugin. Besides that I do not have Windows laptop to check this issue.

At this point and for such type of issues we can only hope that someone in our community can contribute to address it! Let's hope that there will be someone..

**Comment by mburakgurler** [comment]
@mlytvyn firstly thank you for you fast reply, Is there any way do debug plugin for this behaviour.

Is this plugin support Windows, if so I can try to import in Windows then copy .idea folder to WSL for correct extension info and up-to-date indexes.

**Comment by mlytvyn** [comment]
@mburakgurler , absolutely, you can grab latest master, start sandbox IDEA in debug mode and import your project.

Feel free to ping me on project's Slack for quick sync-up if you will need any support.

**Comment by mburakgurler** [comment]
@mlytvyn I'll report my findings, there is definitely problem with WSL. I just copied project to Windows directory and tried to re-import/import from ide. It imported within seconds.

I hope someone in our community already it came across. Otherwise time to learn plugin/kotlin development.

**Comment by mlytvyn** [comment]
@mburakgurler , I was looking for someone with Windows and desire to contribute for last 3 years, with absence of the wsl support you may guess who will be the person I will ask for help now ;)

If you will need any support on this journey feel free to reach me out and I will try to help you start faster.

Thank you!!

**Comment by mburakgurler** [comment]
@mlytvyn I would be happy to contribute. Thank you in advance for your help where I need support. I am starting to prepare my environment.

Thank you
