### ISSUE TITLE
Wrong Class hiearchy shown for model classes when an hierarchy requested from type itself

### ISSUE THREAD

**Issue by viktor-yengovatov** [epam/sap-commerce-intellij-idea-plugin#26]
When some model class is opened and attempt to show type hierarchy leads to wrong subclass hierarchy.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/19975105/122120447-1a032600-ce33-11eb-8255-c7a18f0c58b6.png">

In case the hierarchy for the same class (e.g. ProductModel) is called from different classes' reference (e.g. from VariantProductModel) to the class (ProductModel) it works perfectly.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/19975105/122121089-e248ae00-ce33-11eb-8b22-3daadf2b56bb.png">

**Comment by viktor-yengovatov** [comment]
Adding hybris/bin/platform/bootstrap/**gensrc** as _excluded_ folder seems fixes that. 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/19975105/122121922-d6a9b700-ce34-11eb-8edd-1955e7c775f9.png">

I haven't noticed any downsides of the approach - sources for model classes are still attached.

What do you think if such exclusion would be made by the plugin? 
Do you see any issues with the approach?

**Comment by ghost** [comment]
Exclusion has an impact on indexing, so, I think we can't use this approach. This hierarchy issue sometimes doesn't reproducible, however in most cases works, as you described. As a part of the investigation, could you unmake/make _gensrc_ as "Generated Sources Root" 
![Screenshot from 2021-06-16 20-58-06](https://user-images.githubusercontent.com/53171771/122269552-02d14080-cee6-11eb-8d9f-2cfcbaa42a5c.png)

**Comment by viktor-yengovatov** [comment]
> Exclusion has an impact on indexing

It is a bit unusual, but after excluding this directory products are indexed. Even after invalidating all caches/restart.

> As a part of the investigation, could you unmake/make gensrc as "Generated Sources Root"

It does not help :(

During the analysis I've found the dirrerence of the hierarchy build process:
* for working scenario it takes as target to build the hierarchy as `ProductModel.class` from `models.jar` 
* in case of wrong behavior it takes "ProductModel.java" from the mentioned folder

**Comment by ghost** [comment]
Hmm, looks like smth with indexing that the wrong tree is built. In this case, exclusion may help but looks like a workaround to ignore the _gensrc_ folder. I think that it is better to investigate the process of building a class hierarchy tree.

**Comment by viktor-yengovatov** [comment]
It seems that gensrc directory is already been included in Plafrom Bootstrap by line `model.addRoot(VfsUtil.getUrlForLibraryRoot(bootStrapSrc), OrderRootType.SOURCES);`:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/19975105/122475703-b8c38a00-cfcd-11eb-8db9-809547246b7e.png">

Keeping it non-ignored makes sources duplicates in the three.

I would say it has to be marked as excluded.

**Comment by ghost** [comment]
The fix will be tested in the scope of migration to the 2021.2 version of IDE.

**Comment by ghost** [comment]
Released with 2021.2
