### ISSUE TITLE
Cannot find symbol 

### ISSUE THREAD

**Issue by vicenthy** [epam/sap-commerce-intellij-idea-plugin#283]
Sometimes a have this issue when I run junit test

**Comment by mlytvyn** [comment]
@vicenthy to be able to proceed with this Issue it is preferable to have some extra details, such as: steps to reproduce, exception trace, use case, test project.
Without detailed information it would be quite challenging issue to fix.

**Comment by mlytvyn** [comment]
latest `2023.2*` release contains improved project import logic. please reimport and reopen issue if it will not work
