### ISSUE TITLE
Wrong module structure after importing new hybris project

### ISSUE THREAD

**Issue by rrdas2294** [epam/sap-commerce-intellij-idea-plugin#314]
- **Hybris version**: 2105.18
- **IDE**: Intellij Ultimate 2023.1
- **Plugin version**: Both 2023.1.2 and 2023.1.3
- **OS:** Both  Mac OS Ventura and Windows 10 Pro

Working fine with  2022.xx versions. 
The problem started after updating to the latest versions.
The module structure is not correct after importing the hybris project.
Attached the screenshot.

![image](https://user-images.githubusercontent.com/129557951/229242873-b29eedc9-9fc4-4093-b5a0-68e1fae29a86.png)

**Comment by mlytvyn** [comment]
Hello, @rrdas2294, thank you for reporting this issue.

I'll look to this next week.

Meanwhile, can you please share details about your project structure, are you using any symlinks, etc.?

**Comment by mlytvyn** [comment]
@rrdas2294 , it seems that in case of ccv2 project structure + hybris folder under `core-customize` you have to enable flag "scan all folders" during import, also mentioned by other users - https://github.com/epam/sap-commerce-intellij-idea-plugin/issues/305.

<img width="629" alt="Screenshot 2023-04-01 at 17 20 52" src="https://user-images.githubusercontent.com/2292510/229298225-778e7e35-f336-44fc-90b1-0bff98d5cb5f.png">

**Comment by rrdas2294** [comment]
> @rrdas2294 , it seems that in case of ccv2 project structure + hybris folder under `core-customize` you have to enable flag "scan all folders" during import, also mentioned by other users - #305.
> 
> <img alt="Screenshot 2023-04-01 at 17 20 52" width="629" src="https://user-images.githubusercontent.com/2292510/229298225-778e7e35-f336-44fc-90b1-0bff98d5cb5f.png">

It worked. Thank you.

**Comment by mlytvyn** [comment]
@rrdas2294 , outstanding news! thank you for confirmation!

It seems that we have to add at least some instructions, I'll try to add something in scope of the next `2023.2.0` release.

p.s. "1 star" rating on a plugin page almost ruined me ;) so I'm glad that it works.

**Comment by rrdas2294** [comment]
unfortunately, there is no option to modify the rating.  😞
