### ISSUE TITLE
Do not index node_modules directories

### ISSUE THREAD

**Issue by AleFeher** [epam/sap-commerce-intellij-idea-plugin#39]
With the arrival of SAP Commerce 2105 some npm based extensions got a new directory called apps and inside of it a node_modules directory, this one was taking ages to index on IntelliJ to the point that cache folder was taking more than 9GB of storage and not even near to finish.

After some diging on IntelliJ logs, me and [@danielklava](https://github.com/danielklava), found out what the issue was and, as a temporary solution, marked those directories as _"Excluded"_ to fix the problem, this way we were able to finish indexing and be able to debug the code again.

Searching through the project tab here on GitHub I've found the improvement [_IIP-10_](https://github.com/epam/sap-commerce-intellij-idea-plugin/projects/1#card-54414700) that seems to be related to this problem. Would be nice to have a option to not index those diretories or even be a default option during project import.

Sorry if this is a duplicate issue but at least can be useful for people googling for the same problem.

_How to replicate:_ got this problem while importing or refreshing a project on IntelliJ using the SAP Commerce plugin, to replicate just add some extension to config/localextensions.xml that have the forementioned directory, e.g. smartedit:

`<extension name="smartedit">`

**Comment by anasoid** [comment]
+1,
 it's impossible to import project in Hybris 2105 without excluding all smart-edit projects (smartedittools, personalizationsearchsmartedit, ..)

**Comment by madhopuriam** [comment]
+2 

I was also facing the same issue. Thanks @AleFeher for your suggestion.

**Comment by anasoid** [comment]
As temporary solution you can disable node_module from all projects in intellij.

![image](https://user-images.githubusercontent.com/10306838/158745700-1e436e72-68f9-466e-a587-dce9da338cee.png)
