### ISSUE TITLE
AddOn Classpath issue - IDE unable to correctly handle Java dependencies

### ISSUE THREAD

**Issue by ahalbig** [epam/sap-commerce-intellij-idea-plugin#40]
Usually the dependency as defined in "extensioninfo.xml is representing the java dependencies equally. In case of AddOns it seams to be an big issue. An accelerator is developed you need to define the dependencies of the AddOn within the accelerator, but the AddOn code-wise actually extends the accelerator which means if you write Java code the dependencies are currently not correctly linked within the IDE. The ANT-Script is able to handle that correctly, but because of that unique situation the IDE is unable to build the modules hence also things like hot-swapping, code complition, etc. wont work. 

https://help.sap.com/viewer/b490bb4e85bc42a7aa09d513d0bcb18e/1905/en-US/8acbff4b866910148e4be4ac7412dc83.html 

The issue happens because the build process is scanning for the acceleratoraddon-Folder and is triggering an copy process, that means that what is actually is defined in the config xml as below

**Definition as by extensioninfo.xml**
-> some modules + AddOn A, B, C, D  -> b2b/b2c accelerator 

actually translates to an java classpath

** Actually "applied" ***
-> some modules -> b2b/b2c accelerator -> AddOn A, B, C, D

Is it possible to adjust the plugin handle such special situation to allow the IDE to understand the relationship between AddOn and Extensions?

**Comment by mlytvyn** [comment]
let's hope that it's resolved in the latest release `2023.2.1`, with new project import logic https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/477
