### ISSUE TITLE
Remote Hybris Instance - Unable to obtain session id

### ISSUE THREAD

**Issue by amddsc** [epam/sap-commerce-intellij-idea-plugin#41]
Hi,

when I try to connect to the Remote Hybris Instance running on my localhost I always get an error saying "Unable to obtain sessionId for https://localhost:9002". I can login to hac with this server and credentials without problems. 
Running intellij and commerce instance inside wsl2.

![grafik](https://user-images.githubusercontent.com/95740332/145166887-80dc49a0-ebe3-454d-875c-52428e79f4d7.png)

**Comment by paulograbin** [comment]
I believe this happens only when testing the connection. If you try to import an impex file or running a flexible search query with the same settings it will work. Tested using Commerce 2105, Intellij 2021.3 and latest plugin version.

**Comment by ablil** [comment]
I am having alos this issue, I tried testing the connection and importing impex or running a simple flexible search, but either of them worked for me, is there any solution for this ??
Context: I am using the latest version of both, Intellij Idea and Hybris plugin.

**Comment by rsinghmerkle** [comment]
I am facing the same issue

**Comment by ghost** [comment]
Hello, @amddsc , @paulograbin , @ablil , @rsinghmerkle 
The fix is already available with the newest version of the plugin for IDEA 2022.1 (https://confluence.jetbrains.com/display/IDEADEV/IDEA+2022.1+latest+builds).
Don't forget to change the **SSL protocol** version

**Comment by dorgz** [comment]
Still having this issue. Updated to IJ EAP and latest EPAM plugin version as per screenshot. Tried with many combinations of input ie. changing SSL protocol, SSL on/off, webroots

![Screenshot 2022-03-25 at 14 08 04](https://user-images.githubusercontent.com/2189770/160137642-96cbb48a-67a1-4f82-b2fc-7388dac54888.png)

**Comment by paulograbin** [comment]
@dorgz did you try to run an impex and/or flexible search? Or did you just tried to configure the connection?

I have problems setting up the connection, but I can run a flexible search without any problems.

**Comment by dorgz** [comment]
Unfortunately I get the same error running impex and flexible search. The Solr panel works perfectly though.

**Comment by dorgz** [comment]
Unfortunately I get the same error running impex and flexible search. 

The Solr panel works perfectly though.

**Comment by ghost** [comment]
@dorgz , what version of hybris do you use?

**Comment by dorgz** [comment]
@MykytaKostiuk I'm using version 2011.15

**Comment by dorgz** [comment]
Strangely enough, the plugin started working on my machine using the older IDEA and plugin versions. I haven't changed anything that I'm aware of.

<img width="475" alt="Screenshot 2022-03-27 at 19 25 03" src="https://user-images.githubusercontent.com/2189770/160295270-aed717e7-bcf5-41c3-bc60-48157a68710d.png">

**Comment by leoferreiralima** [comment]
I haved the same problem, i'm using wsl2 with sap commerce cloud 2105 and intellij community 2021.3.3.

i changed the host to wsl2 ip and the TLS version to 1.2 and worked on the second time a have tried do connect.

I believe that first try didn't work because crsf verification.

![image](https://user-images.githubusercontent.com/36305985/162188131-a6f3da2d-41be-4015-926f-3b6d7da0b26c.png)

![image](https://user-images.githubusercontent.com/36305985/162190358-f4fda2ee-c107-4225-817c-557d7adc8d8a.png)

**Comment by LostKatana** [comment]
I have successfully managed to establish a connection to my locally running system.
![image](https://user-images.githubusercontent.com/14800164/208873997-39ef72dc-ca03-42b1-837a-e93edc48de31.png)

In my local.properties I also have this entry: hac.webroot=/hac
Maybe someone can manage to get the connection working like this.

**Comment by khalid-sb** [comment]
i am facing the same problem
hybris version 2205
intelij 2022.3.1
plugin 2022.3.0
![image](https://user-images.githubusercontent.com/20110054/210252149-f5880def-6079-44e0-b672-82aa7101541e.png)

**Comment by mlytvyn** [comment]
for all new configurations default SSL protocol changed to TLSv1.2, also Plugin will try to identify most suitable settings, like Port or webroot based on [y] instance configuration, see https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/143
