### ISSUE TITLE
Unable to import project from existing sources since upgrading to Idea 2023.2

### ISSUE THREAD

**Issue by nkat2112** [epam/sap-commerce-intellij-idea-plugin#526]
I just upgraded to IntelliJ Idea 2023.2 today on my Ubuntu computer. I've verified that I'm using plugin:

SAP Commerce Developers Toolset 2023.2.3

While attempting to import a project from existing sources, and despite the "Scan for SAP Commerce modules even in external modules" checkbox being checked, I see an empty list of modules on the subsequent page of the import wizard with the following window title:

"Select SAP Commerce projects to import"

This prevents me from importing the project.

Furthermore, it seems to coincide with the following exception that can be seen under "IDE Internal Errors":

java.lang.IllegalStateException: Duplicate key adaptivesearchbackoffice (attempted merging values YOotbRegularModuleDescriptor {name=adaptivesearchbackoffice, moduleRootDirectory=/home/MYHOME/dev/hybris/MYPROJECT/core-customize/hybris/bin/modules/adaptive-search/adaptivesearchbackoffice} and YCustomRegularModuleDescriptor {name=adaptivesearchbackoffice, moduleRootDirectory=/home/MYHOME/dev/hybris/MYPROJECT/core-customize/hybris/bin/custom/adaptivesearchbackoffice})

Thank you.

**Comment by mlytvyn** [comment]
@nkat2112 , thank you for reporting this issue, ideally we should not have extensions of the same name.

I have to think what can/should be done in such a case.

**Comment by mlytvyn** [comment]
as an intermediate solution, can you try to uncheck OOTB `adaptivesearchbackoffice` and re-import again?

**Comment by nkat2112** [comment]
Hello, @mlytvyn . Thank you for your response.

No, I cannot because this issue results in NO extensions being shown for me to check/uncheck.

I've had to downgrade Idea and plugin to get past this.

I did notice that the "Scan for SAP Commerce modules even in external modules" checkbox is checked by default with the new plugin, but not in the older plugin. But this observation may have nothing to do with it.

**Comment by mlytvyn** [comment]
I see, thank you, I'll try to fix it and release new version in ~2days

**Comment by listemanuel95** [comment]
I'm experiencing a similar issue (different error though) since upgrading both IDEA and the plugin. Also on Ubuntu.
Some exceptions are thrown, but I think this one might be the culprit:

```
java.lang.ExceptionInInitializerError
	at com.intellij.idea.plugin.hybris.project.configurators.SpringConfigurator.<clinit>(SpringConfigurator.kt)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultConfiguratorFactory.getSpringConfigurator(DefaultConfiguratorFactory.kt:35)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:161)
	...
Caused by: java.lang.NullPointerException: getApplication().getServ…Configurator::class.java) must not be null
	at com.intellij.idea.plugin.hybris.project.configurators.SpringConfigurator$Companion.<clinit>(SpringConfigurator.kt:46)
```

Though I'm getting a warning when starting the import process (some missing plugins), I do get to see the list of all SAP Commerce Projects that are going to be imported, and it looks OK. But after importing, I get the error and see no modules.

The plugin was working fine before upgrading.

Thanks in advance.

**Comment by mlytvyn** [comment]
While I'm working on the issue, could you please try to remove all OTB extensions of duplicate names?

**Comment by mlytvyn** [comment]
@listemanuel95 , thank you for reporting, it is fixed in scope of the #528 (reported as #527)

@nkat2112 , I was able to quickly adjust it, will request new release `2023.2.5`
<img width="600" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/02a5b894-7cbe-4086-9ec8-b8e4de92832a">

**Comment by nkat2112** [comment]
Oh my goodness, @mlytvyn , you totally rock!

Thank you so much!

**Comment by mlytvyn** [comment]
@nkat2112 , @listemanuel95 , can you please try latest `2023.2.5` version?

**Comment by nkat2112** [comment]
Hello, @mlytvyn . I'd love to, but I do not seem to have access to that branch. I only seem to have access to branch 'main'.

This link gives me a 404:

https://github.com/epam/sap-commerce-intellij-idea-plugin/tree/release/2023.2.5

Thanks.

**Comment by mlytvyn** [comment]
@nkat2112 , yeah, it is already released ;) and merged to `main` ;)
https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset/versions/stable/369361

**Comment by listemanuel95** [comment]
It's fixed for me after upgrading to `2023.2.5`.

Thank you!

**Comment by nkat2112** [comment]
Oopsies, thanks for clearing up my misunderstanding, @mlytvyn .

I just checked - it's working for me, thank you so much!

**Comment by mlytvyn** [comment]
thank you for feedback! I'm closing this ticket as resolved.
