### ISSUE TITLE
Readonly mode is broken in IDEA 2023.2 

### ISSUE THREAD

**Issue by sholovii** [epam/sap-commerce-intellij-idea-plugin#532]
Title says it all - readonly mode is broken. Despite files being marked as readonly and project being imported with readonly mode enabled - I'm still able to edit OOTB files.

**IntelliJ version:** 

IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to Serhii Holovii
Subscription is active until May 28, 2024.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Metal Rendering is ON
Registry:
    decompiler.dump.original.lines=true
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.thvardhan.gradianto (5.3)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.142)
    PlantUML integration (6.3.0-IJ2023.2)
    com.intellij.lang.jsgraphql (4.0.2)
    com.nekofar.milad.intellij.nestjs (1.2.20)
    com.intellij.idea.plugin.sap.commerce (2023.2.5)

Kotlin: 232-1.9.0-IJ8660.185

**Plugin version**
2023.2.5

<img width="1443" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/78964781/1cdece4b-c51a-448e-9399-4dc9f045fcf3">

**Comment by mlytvyn** [comment]
@sholovii , thank you for reporting, its tricky :)

**Comment by mlytvyn** [comment]
As this issue is not a "blocker" let's postpone to the next release, fixed in scope of the #533

**Comment by mlytvyn** [comment]
@sholovii , closing this ticket as as fixed on latest `2023.2.6`
