### ISSUE TITLE
2022.2 : Impex no code style and autocompletion

### ISSUE THREAD

**Issue by darkweizer** [epam/sap-commerce-intellij-idea-plugin#58]
Hey !

Since version 2022.2, the impex are read as simple text. There is no more code style and autocompletion.
[https://ibb.co/wC3XtCK](https://ibb.co/wC3XtCK)

Thanks.

**Comment by ghost** [comment]
Hi, could you check please the `File Types` mappings?
![image](https://user-images.githubusercontent.com/53171771/185119347-ee4e9e36-2448-4ac2-8283-fb0a6980ffe6.png)

**Comment by darkweizer** [comment]
Oh yes, is empty for me !
<img width="495" alt="Capture" src="https://user-images.githubusercontent.com/15857329/185122973-b593852b-4886-46bd-9f59-0b03de0703e9.PNG">
But, when I add a new pattern
<img width="277" alt="Capture" src="https://user-images.githubusercontent.com/15857329/185123598-ac34d1e3-7b2d-4f5c-9f3a-d181fa405d75.PNG">
I have this warning message :
<img width="281" alt="Capture" src="https://user-images.githubusercontent.com/15857329/185124290-c225f0c6-6703-4947-92b6-09bc5be5a7be.PNG">

**Comment by ghost** [comment]
So, seems it is used also here: 
![image](https://user-images.githubusercontent.com/53171771/185127133-3c3a3536-bc16-4094-8692-cc6365f48345.png)
To make the plugin work correctly with the *.impex files, the configuration should be as in the first screenshot
`Impex language file -> *.impex`

**Comment by darkweizer** [comment]
Nice ! It's work 👍🏻 
But I don't know why this configuration was changed after updating the plugin in version 2022.2 🤷🏻‍♂️
