### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by jsdevel** [epam/sap-commerce-intellij-idea-plugin#59]
Hi, I'm trying to work on a hybris project with custom extensions and I'm not finding any simple How-To guides.  Can someone point me in the right direction?  Thanks!

**Comment by mlytvyn** [comment]
@jsdevel , starting point for every SAP Commerce Cloud (Hybris) developer is https://help.sap.com/docs/SAP_COMMERCE_CLOUD?locale=en-US

**Comment by nick-ax** [comment]
After struggling with this plugin for a while it popped up with these messages which were very useful...

<img width="393" alt="Screenshot 2022-12-11 at 15 09 05" src="https://user-images.githubusercontent.com/94679980/206914997-d077c040-a78d-47cc-bc4f-cd4ca11264e6.png">

**Comment by jsdevel** [comment]
thank you @nick-ax .  that at least gets me headed in the right direction to use the plugin

**Comment by mlytvyn** [comment]
@jsdevel , everything depends on your setup, project/file structure.

sample flow:
- unpack sap commerce cloud
- Create custom extensions via ant
- Update localextensions.xml
- start Intellij Idea and create sample project anywhere, can be blank, just do not use same folder which was used for sap commerce cloud
- via Idea’s menu create new project from existing sources
- select hybris project type in the import wizard and follow wizard’s steps

p.s. as for now plugin does not support automatic project type identification when one will try to create project via Idea’s new import process.

**Comment by mlytvyn** [comment]
Added few GIF animations on a Plugin page, one of them is how to open project in two ways (Open & via Wizard).

Closing ticket for now, @jsdevel , if you will have any ideas on how to improve docs feel free to share your ideas and contribute to the project!
