### ISSUE TITLE
Wrong Inspections: Backoffice Create Wizard Navigation Buttons

### ISSUE THREAD

**Issue by amddsc** [epam/sap-commerce-intellij-idea-plugin#625]
When adding buttons to the navigation section of a create-wizard the plugin is always given these 2 inspections: 

1. 'save' child tag should be defined.
2. 'save-all' child tag should be defined.

![grafik](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/95740332/f5185658-c8b0-41b0-857f-12bba0e85de2)

Imho, for the button types cancel, next, back & custom this hint doesn't make sense because the save and save-all tags would trigger a save operations for their property-attribute. That is typically the opposite of what you want if you add a cancel button ;)
Also the save-all lint on the done button shouldn't be shown in my opinion. In many create wizards you only save one item and you don't need to use save-all.

**Comment by mlytvyn** [comment]
@amddsc , thank you for reporting this issue, fixed in scope of the #626 .
