### ISSUE TITLE
Compact middle packages not working

### ISSUE THREAD

**Issue by darkweizer** [epam/sap-commerce-intellij-idea-plugin#646]
Hi !

Since 2023.2 version, the empty packages isn't compacted.

Before 2023.2, I had
- level1.level2.level3
  - ClassLevel3

Since 2023.2, I have
- level1
  - level2
    - level3
      - ClassLevel3

I have update IJ in 2023.2.1 and plugin in 2023.2.6 and I have the same problem. Disable plugin fix the issue (also for no SAP project).
I have open a ticket on [IntelliJ bugtracker](https://youtrack.jetbrains.com/issue/IDEA-330612/Compact-middle-packages-not-working) before understanding that the bug came from the plugin.
I see pull request #568 but it's work only for no directory marked or marked excluded
![](https://i.ibb.co/5RxC19N/D-art-d-art-c-est-de-l-art.gif)
Before 2023.2 or with plugin disable :
![Before_2023 2](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/15857329/d610225c-7b19-4826-b883-4f348e3d7b77)
Since 2023.2 and with plugin enable
<img width="412" alt="Since_2023 2" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/15857329/a8d04460-c631-4633-9e3c-6eaa6243c3c7">

Thanks.
Best regards.

**Comment by mlytvyn** [comment]
@darkweizer , thank you for reporting this case, I'll look to it and try to adjust behaviour in the upcoming `2023.2.7`

**Comment by mlytvyn** [comment]
@darkweizer , once again, thank you for reporting this! there are so many changes and so easy to miss something.
there was a change related to CCv2 module structure which caused that issue.

it is fixed here #647 and will be available in the `2023.2.7`

p.s. if you have any other finding or ideas feel free to share, btw there is a Slack channel -> https://github.com/epam/sap-commerce-intellij-idea-plugin

**Comment by darkweizer** [comment]
Oh ! Really fast ^^
Thanks for your responsiveness and especially thanks to you for this great plugin 😉😊🙏🏻
