### ISSUE TITLE
Improve CCv2 SAP Commerce Cloud manifest.json schema support

### ISSUE THREAD

**Issue by oleksiy-dembitskyy** [epam/sap-commerce-intellij-idea-plugin#684]
For the "storefrontAddons" section in the manifest.json file, only the children "addon" and "storefront" are defined.
But according to [SAP documentation](https://help.sap.com/docs/SAP_COMMERCE_CLOUD_PUBLIC_CLOUD/1be46286b36a4aa48205be5a96240672/9a3ab7d08c704fccb7fd899e876d41d6.html) this section can contain "addons" and "storefronts".

**Comment by mlytvyn** [comment]
@oleksiy-dembitskyy , thank you for highlighting this, I'll adjust json schema in scope of the `2023.2.8` release

**Comment by mlytvyn** [comment]
@oleksiy-dembitskyy , done in scope of the #685 and will be available in the upcoming `2023.2.8`.
code completion will be added in a separate PR
