### ISSUE TITLE
Selected Open File is located in junk(virtual directory), not in src

### ISSUE THREAD

**Issue by thetruechar** [epam/sap-commerce-intellij-idea-plugin#741]
Hi, I'm new to commerce cloud and I found this great plugin, but however, when I search for something and click `Selected Open File`, it always shows it located in junk(virtual directory) instead of `src` directory(see the pic), anyone can help me how to configure something which I missing?

<img width="1608" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/9455827/8781de7c-bff5-4607-8b27-f642dbfa77e7">

**Comment by mlytvyn** [comment]
Hello @thetruechar , original version of the plugin will register src dirs for ootb extensions only if project import flag “import ootb extensions in readonly mode” is set to **false**.

Such approach is required to improve compilation time in Idea.

I’ll try to play around with it in the upcoming release to always register src dirs, but mark them as ignored.

**Comment by thetruechar** [comment]
@mlytvyn  thanks for the prompt reply! I just re-imported with `import ootb extensions in readonly mode` enabled, but the location remains the same...
<img width="977" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/9455827/dfe1cd04-4df9-4031-bac3-62c3f25a7b08">
<img width="1608" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/9455827/890fef2c-1d88-4d4f-8eea-9093b0bb4ba6">

**Comment by mlytvyn** [comment]
try to uncheck that flag ;)

**Comment by thetruechar** [comment]
It works after uncheck the flag, you mentioned only if it is set to true, so... anyway, big big thanks for your help!

**Comment by mlytvyn** [comment]
@thetruechar , yeah, my bad, slightly tired. I'll adjust my comment above.

anyway, I'll try to improve classpath resolution even for readonly mode.

GOOD luck on your SAP Commerce journey!!!

**Comment by mlytvyn** [comment]
@thetruechar , looks like Intellij IDEA will not ideally support directories both ignored and registered as sources. Even defining new module lib leads to unexpected issues.

let's leave it as is, if anyone will find a way how to improve classpath resolution it would be great to see such contribution.

closing this ticket, and thank you once again!
