### ISSUE TITLE
Project import not working as expected in 2023.2.8

### ISSUE THREAD

**Issue by dorgz** [epam/sap-commerce-intellij-idea-plugin#749]
Hello, have been having the following issue since upgrading the plugin from `2023.2.0` -> `2023.2.8` on `IntelliJ IDEA 2023.2.2`.

The project import no longer works as expected with our repo structure. Here is the structure for demonstration.

![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2189770/0a4a8119-df63-421d-b5d7-cea9fb5f23b3)

When importing, I am using `/repo` as the root folder (ie. selecting `/repo` from the `New > Project from Existing Sources...` dialog) and overriding the hybris platform and custom folders in the plugin import dialog.

This results in the following message (`hybris.project.import.scan.platform.not.found`):

![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2189770/adb09953-0fbc-41d1-a810-6782b1b47ebe)

This issue goes away when selecting `repo/hybris-platform` from the `New > Project from Existing Sources...` dialog. However this means version control on the project doesn't work as expected and the project is missing lots of other files contained in `/repo`.

Is the nesting of our platform folder simply too deep or is there something else at play here?

**Comment by mlytvyn** [comment]
@dorgz thank you for highlighting this and so detailed sample setup, I’ll try to figure out what can be done in such a case.

**Comment by mlytvyn** [comment]
@dorgz , please reach me out in Slack (link is here https://github.com/epam/sap-commerce-intellij-idea-plugin) 

I've just tried to do the same and it works at my side :(

**Comment by dorgz** [comment]
@mlytvyn thanks for looking into it. I have retested this with some different scenarios and can report the following:

1. Clone repo fresh -> issue persists
2. Copy entire folder structure `/hybris-platform/source/hybris/bin/platform` to new root folder -> issue persists
3. Create new `/hybris-platform` folder and copy existing `/source/hybris/bin/platform` into this -> issue no longer occurs!

For scenarios 2 & 3, the root folder didn't contain any other files or folders and was still able to recreate the issue. Just wanted to rule out interference from other content in the repo

**Comment by mlytvyn** [comment]
@dorgz , interesting and looks like quite dependent on the repo structure,
Locally I tried mostly the 3rd case, so that’s why it could work for me.

Usually I unpack sap commerce, then doing git init, git remote add, git fetch and then checkout to a specific branch.

**Comment by dorgz** [comment]
Yes seems like something specific to our repo structure unfortunately. Can you tell me what this part of the process looks for? Might shed some light on what part of the repo is causing this.

Would also be a nice option if we could manually override/specify this path :))

**Comment by mlytvyn** [comment]
there is combination of the initial code and new code, it may not be an easy to identify what exactly leads to this behaviour without debugging.

we can sync-up in Plugin's Slack and review this issue together.
https://join.slack.com/t/sapcommercede-0kz9848/shared_invite/zt-240ctlx1i-D5ow~z8QMnZUShYM8sxhcw

**Comment by amddsc** [comment]
Hi, 
I am experiencing the same problems but without custom directory override. Also using Intellij Ultimate. Does it mean the issue is fixed in the next version? When will it be released?

**Comment by mlytvyn** [comment]
hello @amddsc , it is not yet fixed as I'm not able to reproduce this issue locally :(

it would be great to sync-up and debug your setup, OR, if you can prepare sample project setup and push it to your GitHub repo it would help a lot.

SAP Commerce version may be important, may be not.

**Comment by amddsc** [comment]
Ok, we've found the cause. In our case it was a custom build.gradle file located inisde the hybris root folder: 
![grafik](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/95740332/7c70a807-3d78-41ba-8678-7be3c5c166ae)
This stops the recursive scan for hybris modules at this directory because with a gradle file in it, it is considered as a non-hybris module, ie gradle project.
temporarily renaming or permantly moving the file to another location solves the problem. 
Thanks again @mlytvyn for your help!

**Comment by mlytvyn** [comment]
@amddsc let's see how it will work in `2023.2.10`, non-[y] modules will be skipped if there are [y] modules in sub folders. 

p.s. CCv2 structure is special, but looks like it also works well.

**Comment by amddsc** [comment]
Hi @mlytvyn, I have just tested it locally with our projects and it works perfectly now. Project import as well as project refresh. Thank you so much!
