### ISSUE TITLE
.editorconfig not fetched

### ISSUE THREAD

**Issue by Jannik-Bohling** [epam/sap-commerce-intellij-idea-plugin#766]
Hi all,

it looks like the .editorconfig is no longer fetched for commerce projects.
For non commerce projects https://www.jetbrains.com/help/idea/editorconfig.html works without any problems.
In the past (e.g. IDEA 2022) it worked like a charm.  

Steps to reproduce:
1. Add a .editorconfig file in your project root 
2. Check if the file is identified by IDEA (e.g. by right clicking on the indents info in the lower right corner)

It would be highly appreciated if you could check if there is an easy fix for this. 

KR

**Comment by mlytvyn** [comment]
hello @Jannik-Bohling , I'm not quite sure what actually does not work, settings applied via `.editorconfig` are respected.
<img width="1532" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/32e9f2e0-3684-4a28-b117-7b1e31d4b768">

for non-SAP CC projects I also do not see button in the "lower right corner".

can you please share screenshots: before vs after?

**Comment by Jannik-Bohling** [comment]
Hi @mlytvyn ,

thanks for the fast reply 🙇 .

For us it looks like the file is not recognized as a project file - see:

![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/13030641/1f753536-4eae-4d0a-93cc-ebee036ed553)

When you open a file with a extension configured in the editor config you get this view: 

Working editor config: 
![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/13030641/ca8bf277-fac0-49f4-8e98-71cdd2c41295)

Non working editor config: 
![image](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/13030641/24b6c38a-8747-4464-9ad6-8fdf9cc46336)

**Comment by mlytvyn** [comment]
ah, you mean this... same case for `.gitignore`

I need to check it.

thanks!

**Comment by mlytvyn** [comment]
@Jannik-Bohling , looks like known issue for other cases -> https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008723039-Project-root-files-not-included-

everything under the root and what is not under any module will be part of the NoProjectScope, I've asked JetBrains for possible way to include such root-level files in the Project Scope, let's see..

one more ref to not fully supported functionality: https://youtrack.jetbrains.com/issue/IJPL-114/Provide-gluing-API-between-platform-and-custom-entities-of-workspace-model-as-of-2023.2

**Comment by Jannik-Bohling** [comment]
HI @mlytvyn,

I can confirm that the search now looks fine, but sadly the file is still a non project file and the config is not fetched.

<img width="499" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/13030641/07bf467d-e391-4ab3-b2fe-1b827002f586">

IDEA: Build #IU-232.10203.10, built on October 24, 2023
Plugin-Version: 2023.2.10

KR
Jannik

**Comment by mlytvyn** [comment]
@Jannik-Bohling , we have two options:
1. Wait for API from JetBrains, it may take several years as practice shows (no offence to colleagues from JetBrains :) )
2. Re-implement project import so it will create root project for top-most project - oh my, I cannot image how much time it may take.

btw, `.editorconfig` is respected by IDEA for my local project setup, feel free to reach me out in the Plugin's Slack to discuss it in details / verbally.
<img width="788" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/d5e4f0fa-5e7b-43f1-bd7b-a49d789f9238">

<img width="1316" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/c0499625-e871-4034-abe9-fba612eb90ff">


Unfortunately, I may not have time to look into it, my open-source passion has its limits :), but if anyone want to contribute I'm more than happy to help with the quick start.

**Comment by mlytvyn** [comment]
@Jannik-Bohling , interesting reply from JetBrains:
> Karol Lewandowski
> Hi, I don't know a way of extending the project scope by plugin. For your use case, try implementing
> com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessExtension.

I'll try that today, stay tuned!

**Comment by mlytvyn** [comment]
@Jannik-Bohling , let's hope that after release 2023.2.11 IntelliJ IDEA will not bother us with that warning for non-project root files.
Please create new ticket if IDEA will not respect `.editorconfig`, ideally - show me your setup. As it works for me :)
