### ISSUE TITLE
IDEA 2023.3 Compatibility

### ISSUE THREAD

**Issue by sholovii** [epam/sap-commerce-intellij-idea-plugin#830]
Plugin is not compatible with the latest IDEA 2023.3

<img width="521" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/78964781/c427cc1f-8674-49e7-9936-e21a8b1819e7">

**Comment by mlytvyn** [comment]
@sholovii , indeed, API is already adjusted, to be released soon.
https://github.com/epam/sap-commerce-intellij-idea-plugin/tree/release/2023.3.0
