### ISSUE TITLE
Problems with Type System items.xml - Not Yet Generated Message

### ISSUE THREAD

**Issue by watzswe** [epam/sap-commerce-intellij-idea-plugin#857]
"Not yet generated" message and Icon is displayed for all custom and standard itemtypes. I have already tried many things, but I can't find a solution to get rid of the message.

Project Setup:
Development Environment: Windows 2016 Server (VM)
SAP Commerce 2205
IntelliJ IDEA 2023.3 (Ultimate Edition)
SAP Commerce Developers Toolset 2023.3.1
JREBEL 2023.4.2

Build SAP Commerce on Command line with ant all
Import SAP Commerce Project with Default Plugin Settings 

All Itemtypes, Enumtypes,.. show the message "Not yet generated".
![items-xml](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/95749464/d307e38c-26c4-4607-94e6-b47c9b99851b)

**Comment by mlytvyn** [comment]
@watzswe , thank you for bringing this up. I may guess that this is related to Windows paths...

Unfortunately, or luckily, I do not have Windows environment and cannot guarantee that the upcoming fix will solve an issue, but I'm crossing my fingers!

**Comment by mlytvyn** [comment]
@watzswe , fix should be available with the next release `2023.3.2`, stay tuned.

https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/860

**Comment by watzswe** [comment]
New release works fine! Thank you.
