### ISSUE TITLE
Project Refresh is failing when build folder exists

### ISSUE THREAD

**Issue by StefanKruk** [epam/sap-commerce-intellij-idea-plugin#861]
We use in our CCv2 Projects the [commerce-gradle-plugin](https://github.com/SAP/commerce-gradle-plugin).

When we run `./gradlew bootstrapPlatform` a `build` folder is created where the extracted  OOTB Modules exists.

When I run `./gradlew cleanPlatform bootstrapPlatform` (because a new Patch of SAP CX is available) and Refresh my Project with `Refresh SAP Commerce Project` via IDE, I only get an empty Project Structure as the Plugin detects duplicate Extensions.

Extensions are available in the build folder and the default `hybris/bin/` folder. I always need to remove the build folder first, before I run the `Refresh SAP Commerce Project`.

Can we exclude `build` folder from getting scanned?

**Comment by mlytvyn** [comment]
@StefanKruk , interesting, I've never used that plugin. Usually, I rely on SAP Commerce `Installer` recipes.

I'll see what can be done, let's hope that it will not take long.

**Comment by mlytvyn** [comment]
@StefanKruk , cannot reproduce with v4.

`core-customize/build` has no Platform related files, only some tmp and hidden `.cache`

<img width="437" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/d6781589-2a1a-4420-93ef-e05583c9ad8f">


```
plugins {
   id("sap.commerce.build") version("4.0.0")
   id("sap.commerce.build.ccv2") version("4.0.0")
}

repositories {
  maven {
     url = uri("https://custom.repo.com/maven")
  }
  flatDir { dirs("dependencies") }
  mavenCentral()
}

CCV2 {
    generatedConfiguration = file("hybris/config")
}
```

**Comment by StefanKruk** [comment]
I will check tomorrow how I can reproduce it. In my case there are the module structure with only extensioninfo.xml in the module folder.

**Comment by mlytvyn** [comment]
@StefanKruk , feel free to reach me out in the Plugin's Slack if more deep testing will be required.

**Comment by StefanKruk** [comment]
@mlytvyn I was now able to reproduce the Issue.
 
```
plugins {
   id("sap.commerce.build") version("4.0.0")
   id("sap.commerce.build.ccv2") version("4.0.0")
}

repositories {
  maven {
     url = uri("https://custom.repo.com/maven")
  }
  flatDir { dirs("dependencies") }
  mavenCentral()
}

CCV2 {
    generatedConfiguration = file("hybris/config")
}

hybris {
    //Control the sparse platform bootstrap.
    //  When enabled, the commerce extensions are extracted from the distribution zip on a as-needed basis.
    //  Only extensions that are actually used in the project (either directly listed in the localextensions.xml or
    //  required by other extensions) are extracted.
    //  The platform itself is always extracted.
    //  When this mode is enabled, the bootstrapInclude configuration property is ignored.
    sparseBootstrap {
        // default is disabled
        enabled = true
        // set of extensions that are always extracted, default is an empty set
        alwaysIncluded = [
                "yempty",
                "yocc",
                "ybackoffice"
        ]
    }
}
```
when sparseBootstrap is enabled, the Gradle Plugin will unzip the extensioninfo.xml to `build/tmp/.cache/expand/zip_<hash>/hybris/bin/modues/....`  to analyze the dependencies.

<img width="536" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/5496227/f22b0d14-adce-44a2-955b-a9665ab9d741">

Seems I can fix this by adding Gradle plugin `java` and calling task `clean` after everything was setup to remove the build folder again.

Maybe it is still possible to ignore the extensioninfo.xml files in the build folder?

**Comment by mlytvyn** [comment]
@StefanKruk , interesting, now it make sense :)

I'll exclude any `hidden` folders from the scanning in the next release

**Comment by mlytvyn** [comment]
@StefanKruk , thank you for highlighting this, stay tuned and wait for `2023.3.2`
