### ISSUE TITLE
Help: How to generate Business Process Diagram?

### ISSUE THREAD

**Issue by LostKatana** [epam/sap-commerce-intellij-idea-plugin#92]
### Question
In the feature list it is stated to be able to generate a Diagram for Business Processes.
_Visualization of business process graph (use context menu of the file "Diagrams/Show Diagram", only Ultimate IDEA)._
How can this be done?

### Current behaviour
Opening the desireds process.xml file and click on Diagram -> Show Diagram opens the Module Dependency Diagram.

### Expected behaviour
Clicking the Show Diagram button visualizes the XML.

### System Setup:
Hybris: v2105
IntelliJ: IntelliJ IDEA 2022.3 (Ultimate Edition) Build #IU-223.7571.182
Desktop: Ubuntu 22.04.1 LTS 64-bit Gnome: 42.5 Wayland

**Comment by mlytvyn** [comment]
@LostKatana , thank you for your input, I haven't worked with this functionality yet so it may take some time to understand what's under the hood

**Comment by mlytvyn** [comment]
@LostKatana , it seems that original code (from ~2016) expects process files to be named in a specific format with exact `process.xml` ending. 
I'll make it ignorecase in the `2022.3.1` version of the plugin

**Comment by LostKatana** [comment]
@mlytvyn Thanks for looking into this.
I will check the latest release to see if this solves our issues and name our process files accordingly.

**Comment by LostKatana** [comment]
@mlytvyn I was already able to verify by renaming the business process, which in our case was name <uniqueName>Process.xml, to <uniqueName>process.xml and <uniqueName>-process.xml that is is an issue wit the case.
Because neither <uniqueName>Process.xml nor <uniqueName>-Process.xml are working.

Thank you very much.
