### ISSUE TITLE
Failure in resolving gensrc models and ootb services

### ISSUE THREAD

**Issue by superpalmi** [epam/sap-commerce-intellij-idea-plugin#982]
Hi,
First of all thank you for your work, I just reinstalled Intellij version 2022.2.5 (Ultimate) and I'm having problems importing my projects, al modules are shown correctly but I have problems resolving ItemModels classes and services, plugin version is 2022.2, do I have to upgrade it? 
![2024-02-01_16-07](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/33351555/2149acdf-14a3-425f-a57a-dba253d9a485)

Thank you

**Comment by mlytvyn** [comment]
Hello, @superpalmi , thank you too for using the Plugin!

Unfortunately, due limited capacity and resources we can support only latest version of IntelliJ IDEA.

There, indeed, were multiple fixes and improvements related to class resolution. It is advisable to perform complete re-import of the project to ensure best user experience.

p.s. feel free to join the Plugin's Slack channel (link in readme.md) if you will need any support, I'll try my best to reply "quickly" enough.

**Comment by mlytvyn** [comment]
@superpalmi , are you still facing this issue? If not, I'll close the issue in ~1 week.
